import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import JoinTeam from "@/utils/JoinTeam";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={` font-Questrial `}>
        <Header />
        {children}
        <div className=" pt-[3rem] px-3 bg-gradient-to-tr from-[#002568]/30 via-blue-50 to-[#fafafa]  ">
          <JoinTeam />
          <Footer />
        </div>
      </body>
    </html>
  );
}
